version: "3.1"

services:
  mariadb:
    image: mariadb:10.11.7
    container_name: config-pro-mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=S3jGVFWYHnFMukB
      - MYSQL_DATABASE=direct-local
      - TS=+00:00
    command:
      # When container is up, make sure lower_case_table_names=0
      # Perform SQL `SHOW GLOBAL VARIABLES LIKE 'lower_case_table_names'` to check it.
      [ "--character-set-server=utf8", "--collation-server=utf8_general_ci", "--lower_case_table_names=0" ]
    ports:
      - "3306:3306"

  redis:
    image: redis:4.0.10
    container_name: config-pro-redis
    restart: always
    environment:
      REDIS_PASSWORD: 'password'
    ports:
      - "6379:6379"
