export enum CpTables {
  CP_PROVIDERS = 'cp_providers',
  CP_PROVIDER_METHODS = 'cp_providerMethods',
  CP_TRANSACTION_CONFIGS = 'cp_transactionConfigs',
  CP_COUNTRY_AUTHORITY_METHODS = 'cp_countryAuthorityMethods',
  CP_COUNTRIES_AUTHORITIES = 'cp_countriesAuthorities',
  CP_FIELDS = 'cp_fields',
  CP_FIELD_OPTIONS = 'cp_fieldOptions',
  CP_AUTHORITIES = 'cp_authorities',
  CP_COUNTRIES = 'cp_countries',
  CP_CURRENCIES = 'cp_currencies',
  CP_METHODS = 'cp_methods',
  CP_PLATFORMS = 'cp_platforms',
  CP_CREDENTIALS = 'cp_credentials',
  CP_PROVIDER_RESTRICTIONS = 'cp_providerRestrictions',
  CP_BANK_ACCOUNTS = 'cp_bankAccounts',
  CP_STP_RULES = 'cp_stpRules',
  CP_STP_PROVIDER_RULES = 'cp_stpProviderRules',
  CP_PROVIDER_FIELDS = 'cp_providerFields',
}
